
language: generic


before_install:
- wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb
- sudo dpkg -i pandoc-1.19.1-1-amd64.deb
# 赋予自动部署脚本可执行权限
- chmod +x .travis/deploy.sh

script:
- bash .travis/deploy.sh

after_success:
# 部署到 GitHub Pages 和 VPS

addons:
  ssh_know_hosts:
  - github.com
  - love4026.org
  apt:
    packages:
    - texlive-xetex
    - texlive-latex-extra
    - texlive-fonts-recommended
    - latex-xcolor
    - latex-cjk-all
    - lmodern
    - texlive-lang-cjk

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    # not support ${qq} can use travis encrypt - secure: ""
    - secure: "N1eZ8JMOijc09xG2rHT9MirXIIFZEs6RCqcvFEPw4MWuc7Lhk/PEcezaZGXZezm8Hs1OCRg+K6ldUU//EPBNIY25Afi+JdvHPsDODkQ6XnCfYADxthaNP5ZRo9Fqbp1XW2gUlCrvB63/McoLJ9wyA/l7Vh/JIIzQXZhKNwN0pkrLnS/f1Jh7jd3eg8Tq7N5SWx+WwC/tgHhHIDG1XHEBq8pLjulvxhMEkx1jlhvJhojEJTI2BvBM7RXxZi1zEAbRG4N/5JmhO5tY63wlRIr5gRjqwSTnOrQPW7+qKPz/0iEbsJ+/2lxNC6rjeRzB/+DWURRXF+HokxZ0Wj0KFRwqJzW3aQ/nG0GHx976cYG05/mX5Zjz4ftYz0VpggMqiDySPW7h2yPBDAlE4oE+8ZTuTafHwNrXVC4s55gJGNJzZ5RejeBCAy2FHTWtXoatfP3DyjjIFgJYsHGKBVEzd7FZEWkkLzQFAdAivD/O4YOfun5cTa1G85+T3DwFjfP9fPp0bxXT2+B6MGLBHe97SYJtrwcxDCD9Ug94Cxby9UwQxHzCbPPv0gMjsyKR9BLFIp/LasruskXEEDOV7qLLyFev18/dSSFlu9OLUX6aBq5TxpVjYMTKJfkvx/QeNXL2Y0PogKJm9DsyvYqfmrQFPqU4Cepbbs2aJoE7ymMl+70ARvo="
    - love4026@gmail.com
  on_success: change
  on_failure: always