
sudo: required
language: generic


before_install:
- wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb
- sudo dpkg -i pandoc-1.19.1-1-amd64.deb
- sudo mkdir -p /usr/share/fonts/opentype/
- sudo wget -P /usr/share/fonts/opentype/ https://github.com/SivilTaram/BUAAOS-guide-book/raw/master/guide-book/fonts/AdobeFangsongStd-Regular.otf
- sudo wget -P /usr/share/fonts/opentype/ "https://github.com/SivilTaram/BUAAOS-guide-book/raw/master/guide-book/fonts/AdobeHeitiStd-Regular%20(v5.010).otf"
- sudo wget -P /usr/share/fonts/opentype/ "https://github.com/SivilTaram/BUAAOS-guide-book/raw/master/guide-book/fonts/AdobeKaitiStd-Regular%20(v5.010).otf"
- sudo wget -P /usr/share/fonts/opentype/ "https://github.com/SivilTaram/BUAAOS-guide-book/raw/master/guide-book/fonts/AdobeSongStd-Light%20(v5.010).otf"
- sudo mkfontscale
- sudo mkfontdir
- sudo fc-cache -f
# 赋予自动部署脚本可执行权限
- chmod +x .travis/deploy.sh
- sudo apt-get install ncftp -y

script:
- bash .travis/deploy.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $REPO_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: resume/build
  on:
    branch: master

# branches:
#   only:
#     - /^v[\d.]+\d$/

after_success:
  # push to ftp
  - pwd
  - ls resume/build/
  - ncftpput -R -v -F -t 60 -u "$FTP_USER" -p "$FTP_PASS" $FTP_HOST / resume/build/resume.pdf

addons:
  ssh_know_hosts:
  - github.com
  - love4026.org
  apt:
    packages:
    - texlive-xetex
    - texlive-latex-extra
    - texlive-fonts-recommended
    - latex-xcolor
    - lmodern
    # - latex-cjk-all
    - texlive-lang-cjk
    # - texlive-fonts-extra

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    # not support ${qq} can use travis encrypt - secure: ""
    - secure: "N1eZ8JMOijc09xG2rHT9MirXIIFZEs6RCqcvFEPw4MWuc7Lhk/PEcezaZGXZezm8Hs1OCRg+K6ldUU//EPBNIY25Afi+JdvHPsDODkQ6XnCfYADxthaNP5ZRo9Fqbp1XW2gUlCrvB63/McoLJ9wyA/l7Vh/JIIzQXZhKNwN0pkrLnS/f1Jh7jd3eg8Tq7N5SWx+WwC/tgHhHIDG1XHEBq8pLjulvxhMEkx1jlhvJhojEJTI2BvBM7RXxZi1zEAbRG4N/5JmhO5tY63wlRIr5gRjqwSTnOrQPW7+qKPz/0iEbsJ+/2lxNC6rjeRzB/+DWURRXF+HokxZ0Wj0KFRwqJzW3aQ/nG0GHx976cYG05/mX5Zjz4ftYz0VpggMqiDySPW7h2yPBDAlE4oE+8ZTuTafHwNrXVC4s55gJGNJzZ5RejeBCAy2FHTWtXoatfP3DyjjIFgJYsHGKBVEzd7FZEWkkLzQFAdAivD/O4YOfun5cTa1G85+T3DwFjfP9fPp0bxXT2+B6MGLBHe97SYJtrwcxDCD9Ug94Cxby9UwQxHzCbPPv0gMjsyKR9BLFIp/LasruskXEEDOV7qLLyFev18/dSSFlu9OLUX6aBq5TxpVjYMTKJfkvx/QeNXL2Y0PogKJm9DsyvYqfmrQFPqU4Cepbbs2aJoE7ymMl+70ARvo="
    - love4026@gmail.com
  on_success: change
  on_failure: always
