name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          working_directory: resume/
          work_in_root_file_dir: true
          extra_fonts: |
            ./fonts/*.otf
      
      - name: resume for web dev
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume-front-end.tex
          working_directory: resume/
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      
      - name: Gather build artifacts
        run: |
          mkdir build
          ls
          mv resume/*.pdf build/
          mv resume/*.png build/
          cp -r README.md build/
      - name: Publish to GitHub pages
        if: success() && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}