name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume/resume.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          extra_fonts: |
            ./fonts/*.otf
      
      - name: resume for web dev
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume/resume-front-end.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      
      - name: Gather build artifacts
        run: |
          mkdir build
          mv *.pdf build/
          mv *.png build/
          cp -r README.md .github/_config.yml build/
      - name: Publish to GitHub pages
        if: success() && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}